- name: Configuration interface "Host-Only"
  template:
    src: ../templates/eth1.network.j2
    dest: /etc/systemd/network/eth1.network
  become: yes

- name: Mise en fonctionnement de l'interface "Host-Only"
  systemd: 
    name: systemd-networkd
    state: restarted
  become: yes
  