---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: Client
    hostname: Client
    box: centos/7
    memory: 1024
    cpus: 1
    interfaces:
      - auto_config: true
        network_name: private_network
        ip: 192.168.59.5
  - name: Attaquant
    hostname: Attaquant
    box: centos/7
    memory: 1024
    cpus: 1
    interfaces:
      - auto_config: true
        network_name: private_network
        ip: 192.168.79.15
provisioner:
  name: ansible
  options:
    v: True
  lint:
    name: ansible-lint

verifier:
  name: testinfra
  lint:
    name: flake8